name: Keep Render App Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping the app
      run: |
        curl -f https://group4-weatherapp.onrender.com || exit 1
        echo "App pinged successfully at $(date)"